version: '3.5'

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=${SERVERURL:-192.168.1.58}
      - SERVERPORT=${SERVERPORT:-51820} #optional
      - PEERS=${PEERS:-254} #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.10.30.0} #optional
      - ALLOWEDIPS=${ALLOWEDIPS:-0.0.0.0/0} #optional
    volumes:
      - ./clients:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
        chatsubo-gate:
        default:

  gate:
    build: .
    user: root
    ports:
      - "${CHATSUBO_GATE_PORT:-7474}:8000"
    environment:
      - ENV=production
      - CHATSUBO_DATABASE_URL=sqlite:///data/chatsubo-gate.db
    volumes:
      - ./config.yml:/opt/chatsubo-gate/config.yml:ro
      - ./data/:/opt/chatsubo-gate/app/data/
      - ./clients/:/opt/chatsubo-gate/clients:ro
    networks:
        default:

networks:
    chatsubo-gate:
      name: chatsubo-gate
    default:
